name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create Ansible credentials.
        id: credentials
        run: |
          sed -i 's|PRIVKEY|${{ secrets.ANSIBLE_PRIVATE_KEY }}|' docker/ansible/run.sh
          sed -i 's|PUBKEY|${{ secrets.ANSIBLE_PUBLIC_KEY }}|' docker/ansible/run.sh
          sed -i 's|WEBHOOK_URL|${{ secrets.ANSIBLE_WEBHOOK_URL }}|' docker/ansible/run.sh

      - name: Install packages.
        id: packages
        ryb: |
          apt-get update
          apt-get install openssh-client curl python3 -y
      
      - name: Configure credentials.
        id: credentials
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.ANSIBLE_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          sed -i 's/\\n/\n/g' ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa*

      - name: Install and run Ansible in check mode for Pull Request.
        id: ansible-check
        if: github.event_name == 'pull_request'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible
          cd ansible
          ansible-playbook playbook.yml --inventory inventory --check > log.txt
      
      - name: Send check output to Teams for Pull Request.
        id: teams-check
        if: github.event_name == 'pull_request'
        run: |
          TITLE="Ansible Check Output"
          MESSAGE=$(cat log.txt | sed 's/"/\"/g' | sed "s/'/\'/g")
          JSON="{\"title\": \"${TITLE}\", \"text\": \"${MESSAGE}\"}"
          curl -H "Content-Type: application/json" -d "${JSON}" "${{ secrets.ANSIBLE_WEBHOOK_URL }}"
      
      - name: Install and run Ansible in live mode for Main.
        id: ansible-live
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible
          cd ansible
          ansible-playbook playbook.yml --inventory inventory --check > log.txt
      
      - name: Send live output to Teams for Main.
        id: teams-live
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          TITLE="Ansible Output"
          MESSAGE=$(cat log.txt | sed 's/"/\"/g' | sed "s/'/\'/g")
          JSON="{\"title\": \"${TITLE}\", \"text\": \"${MESSAGE}\"}"
          curl -H "Content-Type: application/json" -d "${JSON}" "${{ secrets.ANSIBLE_WEBHOOK_URL }}"
