name: Ansible

on:
  workflow_call:
    secrets:
      ANSIBLE_PRIVATE_KEY:
        required: true
      ANSIBLE_PUBLIC_KEY:
        required: true
      ANSIBLE_WEBHOOK_URL:
        required: true

jobs:
  ansible:
    name: Ansible
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Checkout.
        uses: actions/checkout@v2

      - name: Install packages.
        id: packages
        run: |
          sudo apt-get update
          sudo apt-get install openssh-client curl python3 -y
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible
      
      - name: Configure credentials.
        id: credentials
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.ANSIBLE_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          sed -i 's/\\n/\n/g' ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa*
      
      - name: Run Ansible in check mode for Pull Request.
        id: ansible-check
        if: github.event_name == 'pull_request'
        run: |
          cd ansible
          ansible-playbook playbook.yml --inventory inventory --check > log_check.txt
        continue-on-error: true
      
      - name: Clear check credentials.
        id: clear-check
        if: github.event_name == 'pull_request'
        run: |
          rm -f ~/.ssh/id_rsa*
      
      - name: Process check output.
        id: vars-check
        if: github.event_name == 'pull_request'
        run: |
          content=$(cat ansible/log_check.txt)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo ::set-output name=log-check::$content

      - name: Update Pull Request.
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          CHECK: "ansible\n${{ steps.vars-check.outputs.log-check }}"
        with:
          script: |
            const output = `#### Ansible Check 🖌\`${{ steps.ansible-check.outcome }}\`

            <details><summary>Show Check</summary>

            \`\`\`\n
            ${process.env.CHECK}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      - name: Ansible check status.
        if: steps.ansible-check.outcome == 'failure'
        run: exit 1
      
      - name: Run Ansible in live mode for deployment.
        id: ansible-live
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd ansible
          ansible-playbook playbook.yml --inventory inventory > log_live.txt
      
      - name: Clear live credentials.
        id: clear-live
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          rm -f ~/.ssh/id_rsa*
      
      - name: Process live output.
        id: vars-live
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          content=$(cat ansible/log_live.txt)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo ::set-output name=log-live::$content
      
      - name: Send live output to Teams for deployment.
        id: teams-live
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          TITLE="Ansible Pipeline Output"
          MESSAGE=$(echo "${{ steps.vars-live.outputs.log-live }}" | sed 's/"/\"/g' | sed "s/'/\'/g")
          JSON="{\"title\": \"${TITLE}\", \"text\": \"${MESSAGE}\"}"
          curl -H "Content-Type: application/json" -d "${JSON}" "${{ secrets.ANSIBLE_WEBHOOK_URL }}"
