name: CICD

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  packer:
    name: Packer
    uses: ./.github/workflows/packer.yml
  
  terraform:
    name: Terraform
    uses: ./.github/workflows/terraform.yml
    needs: Packer
  
  ansible:
    name: Ansible
    uses: ./.github/workflows/ansible.yml
    needs: Terraform
