name: CICD

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  packer:
    name: Packer
    uses: ./.github/workflows/packer.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
  terraform:
    name: Terraform
    uses: ./.github/workflows/terraform.yml
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
    needs: Packer
  
  ansible:
    name: Ansible
    uses: ./.github/workflows/ansible.yml
    secrets:
      ANSIBLE_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
      ANSIBLE_PUBLIC_KEY: ${{ secrets.ANSIBLE_PUBLIC_KEY }}
      ANSIBLE_WEBHOOK_URL: ${{ secrets.ANSIBLE_WEBHOOK_URL }}
    needs: Terraform

# Updated at 1647533608
