name: CICD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  
  terraform:
    name: Terraform
    uses: ./.github/workflows/terraform.yml
    with:
      env: test
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
  
  packer:
    name: Packer
    needs: terraform
    uses: ./.github/workflows/packer.yml
    with:
      env: test
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ANSIBLE_PRIVATE_KEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
      ANSIBLE_PUBLIC_KEY: ${{ secrets.ANSIBLE_PUBLIC_KEY }}
      ANSIBLE_WEBHOOK_URL: ${{ secrets.ANSIBLE_WEBHOOK_URL }}
  
  ansible:
    name: AnsibleContainer
    needs: packer
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Run Ansible Container
        id: run-ansible
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 531133914787.dkr.ecr.us-east-1.amazonaws.com
          docker pull 531133914787.dkr.ecr.us-east-1.amazonaws.com/packer-test:latest
          docker run 531133914787.dkr.ecr.us-east-1.amazonaws.com/packer-test:latest
          docker rm -vf $(docker ps -aq)
          docker rmi -f $(docker images -aq)
          rm -f ~/.docker/config.json
      
      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          CHECK: "ansible\n${{ steps.run-ansible.outputs.stdout }}"
        with:
          script: |
            const output = `#### Ansible Container Execution 🖌\`${{ steps.run-ansible.outcome }}\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Ansible Check Status
        if: steps.run-ansible.outcome == 'failure'
        run: exit 1
