name: CICD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packer:
    name: CICD
    runs-on: ubuntu-latest
    environment: test
    steps:

      - name: Packer
        uses: ./.github/workflows/packer.yml
      
      - name: Terraform
        uses: ./.github/workflows/terraform.yml
        needs: Packer
      
      - name: Ansible
        uses: ./.github/workflows/ansible.yml
        needs: Terraform
