name: Packer

on:
  workflow_call:
    inputs:
      enviro:
        required: true
        type: string
      region:
        required: true
        type: string
      ecr:
        required: true
        type: string
      family:
        required: true
        type: string
      default_tag:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      ANSIBLE_PRIVATE_KEY:
        required: true
      ANSIBLE_PUBLIC_KEY:
        required: true
      ANSIBLE_WEBHOOK_URL:
        required: true

env:
  PACKER_TEMPLATE: packer/docker-python.pkr.hcl
  RUN_FILE: ansible/run.sh
  ID_RSA: ansible/id_rsa
  ID_RSA_PUB: ansible/id_rsa.pub
  DOCKER_JSON: ~/.docker/config.json

jobs:
  packer:
    name: Packer
    runs-on: ubuntu-latest
    environment: ${{ inputs.enviro }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      # install Packer
      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer -y
      
      # run Packer checks
      - name: Run Packer Checks
        id: packer-check
        run: |
          packer init packer
          packer fmt packer
          packer validate packer/docker-python.pkr.hcl
      
      - name: Update Packer Template
        id: packer-template
        run: |
          sed -i 's|ECR_REPO|${{ inputs.ecr }}|g' $PACKER_TEMPLATE
          sed -i 's|DEFAULT_TAG|${{ inputs.default_tag }}|g' $PACKER_TEMPLATE
          sed -i 's|FAMILY|${{ inputs.family }}|g' $PACKER_TEMPLATE
      
      - name: Configure Credentials
        id: credentials-create
        run: |
          sed -i 's|AWS_ACCESS_KEY_ID|${{ secrets.AWS_ACCESS_KEY_ID }}|' $PACKER_TEMPLATE
          sed -i 's|AWS_SECRET_ACCESS_KEY|${{ secrets.AWS_SECRET_ACCESS_KEY }}|' $PACKER_TEMPLATE
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > $ID_RSA
          echo "${{ secrets.ANSIBLE_PUBLIC_KEY }}" > $ID_RSA_PUB
          sed -i 's|\\n|\n|g' $ID_RSA
          sed -i 's|ANSIBLE_WEBHOOK_URL|${{ secrets.ANSIBLE_WEBHOOK_URL }}|' $RUN_FILE

      # run Packer build for PR
      - name: Run Packer Build for PR
        id: packer-build-pr
        if: github.event_name == 'pull_request'
        run: |
          sed -i 's|ANSIBLE_TITLE|Ansible Container Check Output|' $RUN_FILE
          sed -i 's|ANSIBLE_CMD|ansible-playbook playbook.yml --inventory inventory --check|' $RUN_FILE
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${{ inputs.ecr }}
          packer build $PACKER_TEMPLATE
          sed -i 's|Ansible Container Check Output|ANSIBLE_TITLE|' $RUN_FILE
          sed -i 's|ansible-playbook playbook.yml --inventory inventory --check|ANSIBLE_CMD|' $RUN_FILE

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          script: |
            const output = `#### Packer Format and Style 🖌\`${{ steps.packer-check.outcome }}\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Packer Check Status
        if: steps.packer-check.outcome == 'failure'
        run: exit 1

      # run Packer build for deploy
      - name: Run Packer Build for Deploy
        id: packer-build-deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          sed -i 's|ANSIBLE_TITLE|Ansible Container Deploy Output|' $RUN_FILE
          sed -i 's|ANSIBLE_CMD|ansible-playbook playbook.yml --inventory inventory|' $RUN_FILE
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 531133914787.dkr.ecr.us-east-1.amazonaws.com
          packer build $PACKER_TEMPLATE
          sed -i 's|Ansible Container Deploy Output|ANSIBLE_TITLE|' $RUN_FILE
          sed -i 's|ansible-playbook playbook.yml --inventory inventory|ANSIBLE_CMD|' $RUN_FILE
      
      - name: Clear Credentials
        id: credentials-clear
        run: |
          sed -i 's|${{ secrets.AWS_ACCESS_KEY_ID }}|AWS_ACCESS_KEY_ID|' $PACKER_TEMPLATE
          sed -i 's|${{ secrets.AWS_SECRET_ACCESS_KEY }}|AWS_SECRET_ACCESS_KEY|' $PACKER_TEMPLATE
          echo " " > $ID_RSA
          echo " " > $ID_RSA_PUB
          sed -i 's|${{ secrets.ANSIBLE_WEBHOOK_URL }}|ANSIBLE_WEBHOOK_URL|' $RUN_FILE
          rm -f $DOCKER_JSON
