name: Terraform-Packer

on:
  workflow_call:
    inputs:
      enviro:
        required: true
        type: string
      username:
        required: true
        type: string
      launch_type:
        required: true
        type: string
      family:
        required: true
        type: string
      default_tag:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      TF_API_TOKEN:
        required: true
      TF_GITHUB_TOKEN:
        required: true

env:
  AWS_FILE: variables.tf
  VARIABLES_FILE: modules/container/variables.tf

jobs:
  terraform:
    name: Terraform-Packer
    runs-on: ubuntu-latest
    environment: ${{ inputs.enviro }}
    defaults:
      run:
        working-directory: ./terraform/packer
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Update Variables
        id: variables
        run: |
          sed -i 's|USERNAME|${{ inputs.username }}|g' $VARIABLES_FILE
          sed -i 's|LAUNCH_TYPE|${{ inputs.launch_type }}|g' $VARIABLES_FILE
          sed -i 's|DEFAULT_TAG|${{ inputs.default_tag }}|g' $VARIABLES_FILE
          sed -i 's|FAMILY|${{ inputs.family }}|g' $VARIABLES_FILE
      
      - name: Configure Credentials
        id: credentials-create
        run: |
          sed -i 's|ACCOUNT_ID|${{ secrets.AWS_ACCOUNT_ID }}|g' $VARIABLES_FILE
          sed -i 's|AWS_ACCESS_KEY_ID|${{ secrets.AWS_ACCESS_KEY_ID }}|' $AWS_FILE
          sed -i 's|AWS_SECRET_ACCESS_KEY|${{ secrets.AWS_SECRET_ACCESS_KEY }}|' $AWS_FILE

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.TF_GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve
      
      - name: Clear Credentials
        id: credentials-clear
        run: |
          sed -i 's|${{ secrets.AWS_ACCOUNT_ID }}|ACCOUNT_ID|g' $VARIABLES_FILE
          sed -i 's|${{ secrets.AWS_ACCESS_KEY_ID }}|AWS_ACCESS_KEY_ID|' $AWS_FILE
          sed -i 's|${{ secrets.AWS_SECRET_ACCESS_KEY }}|AWS_SECRET_ACCESS_KEY|' $AWS_FILE
